AWSTemplateFormatVersion: 2010-09-09
Parameters:
  UserPoolId:
    Type: String
  UserGroupName:
    Type: String
  Description:
    Type: String

Resources:
  # User Pool Group Configuration
  CognitoUserPoolGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      UserPoolId: !Ref UserPoolId
      GroupName: !Ref UserGroupName
      Description: !Ref Description
      Precedence: 0