create-cognito-user-pool-and-client:
	aws cloudformation create-stack --stack-name create-cognito-user-pool-and-client \
	--template-body file://createCognitoUserPoolAndClient.yml \
	--capabilities CAPABILITY_NAMED_IAM \
	--region ap-northeast-1