spring:
  application:
    name: authentication-demo

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

          cognito:
            client-id: ${COGNITO_CLIENT_ID}
            client-secret: ${COGNITO_CLIENT_SECRET}
            scope:
              - openid
            redirect-uri: http://localhost:8080/login/oauth2/code/cognito
            authorization-grant-type: authorization_code

        provider:
          cognito:
            issuer-uri: https://cognito-idp.ap-northeast-1.amazonaws.com/${COGNITO_USER_POOL_ID}
            authorization-uri: ${COGNITO_DOMAIN}/login

logging:
  level:
    root: info
    org:
      springframework:
        security: debug

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  session-token: ${AWS_SESSION_TOKEN}
  cognito:
    region: ${COGNITO_REGION}
    user-pool-id: ${COGNITO_USER_POOL_ID}
